var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/goals/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0j8j0qx._.js")
R.c("server/chunks/ssr/0p91_next_dist_esm_build_templates_app-page_0q0uhxr.js")
R.c("server/chunks/ssr/[root-of-the-server]__046z~8n._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-100p9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0fbshku._.js")
R.c("server/chunks/ssr/0p91_next_dist_client_components_0fxmizk._.js")
R.c("server/chunks/ssr/0p91_next_dist_client_components_builtin_forbidden_0bh5o39.js")
R.c("server/chunks/ssr/0p91_next_dist_client_components_builtin_unauthorized_01vs8mb.js")
R.c("server/chunks/ssr/0p91_next_dist_client_components_builtin_global-error_03n.6~~.js")
R.c("server/chunks/ssr/_next-internal_server_app_goals_[id]_page_actions_10u_brm.js")
R.m(94556)
module.exports=R.m(94556).exports
