var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/auth/sign-up-success/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0zk65tu._.js")
R.c("server/chunks/ssr/_0so8z0c._.js")
R.c("server/chunks/ssr/0p91_next_dist_esm_build_templates_app-page_065ky7u.js")
R.c("server/chunks/ssr/[root-of-the-server]__046z~8n._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-100p9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0fbshku._.js")
R.c("server/chunks/ssr/0p91_next_dist_client_components_0fxmizk._.js")
R.c("server/chunks/ssr/0p91_next_dist_client_components_builtin_forbidden_0bh5o39.js")
R.c("server/chunks/ssr/0p91_next_dist_client_components_builtin_unauthorized_01vs8mb.js")
R.c("server/chunks/ssr/0p91_next_dist_client_components_builtin_global-error_03n.6~~.js")
R.c("server/chunks/ssr/_next-internal_server_app_auth_sign-up-success_page_actions_0.7ni6d.js")
R.m(16091)
module.exports=R.m(16091).exports
